[2025-08-06T01:50:15.918+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_metrics.load_labeled_transactions_raw manual__2025-08-06T01:50:02.784766+00:00 [queued]>
[2025-08-06T01:50:16.368+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_metrics.load_labeled_transactions_raw manual__2025-08-06T01:50:02.784766+00:00 [queued]>
[2025-08-06T01:50:16.369+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-08-06T01:50:16.382+0000] {taskinstance.py:2214} INFO - Executing <Task(AirbyteTriggerSyncOperator): load_labeled_transactions_raw> on 2025-08-06 01:50:02.784766+00:00
[2025-08-06T01:50:16.388+0000] {standard_task_runner.py:60} INFO - Started process 6499 to run task
[2025-08-06T01:50:16.390+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'customer_metrics', 'load_labeled_transactions_raw', 'manual__2025-08-06T01:50:02.784766+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/customer_metrics.py', '--cfg-path', '/tmp/tmp5kwmj4og']
[2025-08-06T01:50:16.392+0000] {standard_task_runner.py:88} INFO - Job 58: Subtask load_labeled_transactions_raw
[2025-08-06T01:50:16.444+0000] {task_command.py:423} INFO - Running <TaskInstance: customer_metrics.load_labeled_transactions_raw manual__2025-08-06T01:50:02.784766+00:00 [running]> on host a4babef49899
[2025-08-06T01:50:16.533+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='customer_metrics' AIRFLOW_CTX_TASK_ID='load_labeled_transactions_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-08-06T01:50:02.784766+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-06T01:50:02.784766+00:00'
[2025-08-06T01:50:16.546+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:50:18.234+0000] {airbyte.py:86} INFO - Job 8 was submitted to Airbyte Server
[2025-08-06T01:50:18.235+0000] {airbyte.py:88} INFO - Waiting for job 8 to complete
[2025-08-06T01:50:21.491+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:50:25.638+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:50:52.243+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:50:55.455+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:50:58.484+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:51:01.506+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:51:04.529+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:51:07.569+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:51:10.595+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:51:13.631+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:51:16.672+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:51:19.714+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:51:22.736+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:51:25.762+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:51:28.784+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:51:31.806+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:51:34.830+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:51:37.870+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:51:40.898+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:51:43.936+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:51:46.972+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:51:50.025+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:51:53.058+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:51:56.083+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:51:59.123+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-06T01:51:59.159+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/airbyte/operators/airbyte.py", line 111, in execute
    hook.wait_for_job(job_id=self.job_id, wait_seconds=self.wait_seconds, timeout=self.timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 141, in wait_for_job
    raise Exception(f"Encountered unexpected state `{state}` for job_id `{job_id}`")
Exception: Encountered unexpected state `failed` for job_id `8`
[2025-08-06T01:51:59.200+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=customer_metrics, task_id=load_labeled_transactions_raw, execution_date=20250806T015002, start_date=20250806T015015, end_date=20250806T015159
[2025-08-06T01:51:59.262+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 58 for task load_labeled_transactions_raw (Encountered unexpected state `failed` for job_id `8`; 6499)
[2025-08-06T01:51:59.294+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-06T01:51:59.357+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
